#!/usr/bin/env bash
function join { local IFS="$1"; shift; echo "$*"; }

echo "Welcome in Makemakefile!"
BASEDIR=$(dirname "$0")
cd "${BASEDIR}/../"
TMPMAKE=./misc/Makefile
echo "Temporary makefile will be saved at: ${TMPMAKE}"
FINALMAKE=./Makefile
MAKEFILE=$(cat ${FINALMAKE})
echo "Final makefile will be saved at: ${FINALMAKE}"
IFS=$'\n'
GENERATEDSWITCH=0
rm -f ${TMPMAKE}
touch ${TMPMAKE}
DONESWITCH=0
for j in $(echo "${MAKEFILE}" | cat)
do
	if [ "$j" == "# ==================== GENERATED SECTION ======================================" ]; then
		GENERATEDSWITCH=1
		echo "$j" >> $TMPMAKE
	elif [ "$j" == "# =============== PROJECT CONFIGURATION SECTION ===============================" ]; then
		echo "$j" >> $TMPMAKE
		GENERATEDSWITCH=0
	elif [ "$GENERATEDSWITCH" == "1" ]; then
		if [ "${j:0:7}" == "# =====" ]; then
			echo "$j" >> $TMPMAKE
		else
			if [ "$DONESWITCH" == "0" ]; then
			echo "CSRC		:= $(join "\\ \n"  $(find "./src" -iname "*.c"))
CXXSRC		:= $(join "\\		"  $(find "./src" -iname "*.cpp"))
TESTSRC		:= $(join "\\ \n"  $(find "./misc/tests" -iname "*.cpp"))">> $TMPMAKE
				DONESWITCH=1
			fi;
		fi
	else
		echo "$j" >> $TMPMAKE
	fi

done
